theme = "halve-z"
base_url = "https://deckmoss.github.io"
title = "weblog"
description = ""
default_language = "de"
author = "Michael Fröhlich"

compile_sass = true
minify_html = true
generate_feeds = true
build_search_index = true
generate_sitemap = true
hard_link_static = false

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[search]
include_title = true
include_description = true
include_path = false
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "OneHalfDark", filename = "syntax-theme-dark.css" },
    { theme = "OneHalfLight", filename = "syntax-theme-light.css" },
]
render_emoji = true
external_links_target_blank = true

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
locale = "de_DE"
logo = "icon-192x192.png"
manifest = "manifest.json"
read_time = true
toc = true
csp = true

[extra.placeholders]
tags = false
subtitle = false

[extra.home]
title1 = "ganz󱜙"
title2 = "direkt"
subtitle = "╼weblog╾"
glitch = true #false
logo = { enabled = false, height = "100", width = "100" }
footer = true

[extra.images]
home = "c1tyh4ll.png" #"c1tyh4ll.png" #https://failsafe.monster/c1tyh4ll.png
post_list =  "obsidian.png"#"obsidian_sphere.gif"#"tc2_gv.png" #https://failsafe.monster/bk-prk.jpg
default_post = "ffmultra.gif"#"bk-prk.png" #https://failsafe.monster/bk-prk.jpg
categories = [
    { name = "media", image = "https://raw.githubusercontent.com/bearcott/8bit-art/master/cities/urban.gif" },
]

[extra.menu]
posts = true
posts_label = "Posts"
links = [
    { name = "Code", url = "/projects/" },
]

[extra.footer]
enabled = true
author = true
copyright = true
hash = true
stack = true
links = [
    { name = "posts", url = "/posts/" },
]

#[extra.social]
#email = "codeeeee@posteo.it"
#mastodon = "server/@user_name"
#twitter = "user_name"
#facebook = "user_name"
#codeberg = "username"
#github = "user_name"
#gitlab = "user_name"
#bitbucket = "user_name"
#stackoverflow = "12345/user_name"
#linkedin = "user_name"
#instagram = "user_name"
#lastfm = "user_name"
#twitch = "user_name"
#reddit = "user_name"
##flickr = "user_name"
#keybase = "user_name"
#hackernews = "user_name"
#
#[extra.mastodon]
#author = "@user@server"

[extra.comments]
system = "Linux"

[extra.comments.cactus]
site = "site_name"
page_size = 10
guest_posting = true
update_interval = 0

[extra.comments.giscus]
repo = "deckmoss/gh-pages"
repo_id = ""
category = "Comments"
category_id = ""
mapping = "pathname"
strict = "1"
reactions = "1"
lang = "en"
